### ISSUE TITLE
june29の課題図書 : 製品開発力 - 自動車産業の「組織能力」と「競争力」の研究

### ISSUE THREAD

**Issue by june29** [pepabo/product-ownership-study#8]
2015年夏季の課題図書はこれに決めた！

【増補版】製品開発力―自動車産業の「組織能力」と「競争力」の研究
http://www.amazon.co.jp/dp/4478001936

**Comment by june29** [comment]
夏休み中に読み終わらなかったので、引き続き読みます :bookmark:

**Comment by june29** [comment]
夏休み中に読み終わらなかったので、引き続き読みます :bookmark:

**Comment by june29** [comment]
書籍「製品開発力」を読んだ - 29%の純情な感情
http://june29.hatenablog.jp/entry/2015/09/07/082626

**Comment by kenchan** [comment]
close~
